### ISSUE TITLE
Frostwolf Wolf Riders bugged

### ISSUE THREAD

**Issue by esvedesz** [elysium-project/classic-bug-tracker#433]
Hello,
in Alterac Valley you can summon wolf riders (50 wolves tamed + 25 ram hides). Sad part is you can do it only once per BG. Next summons will be bugged and Frostwolf Wolf Rider Commander will not move from his location. Wolf Riders will spawn and allign but they will also remain in position. The only way to move them is if someone aby accident agroes them (which night impossible).

**Comment by Rubmywrinklz** [comment]
can confirm. also had this issue

**Comment by Terranzin** [comment]
Regarding 50 tames wolves + 25 ram hides, it needs to be the exact same amount, so if you hand in 25 ram hides it should only need 25 tames wolves. 

But I think I know the reason behind it, I´ve handed in over 30 tames wolves together with 50 ram hides but it wont start the first time. And the reason behind this is because I did not actually hand in the tames wolves quest each time, instead I spoke to her and I obtained another muzzle. But if you hand in the quest everytime (which you should do first) then it seems to count fine.

**Comment by Osstinthax** [comment]
I think the problem may be deeper than that, after turn in they will not move. [https://imgur.com/a/xF6Go](url)
