### ISSUE TITLE
Winter Squid catch rate not Blizz-Like in Azshara (Bay of Storms)

### ISSUE THREAD

**Issue by nexiros** [elysium-project/classic-bug-tracker#476]
https://legacy-wow.com/fishing-guide-catching-winter-squid/

The catch rate for Winter Squid seems to be completely off between the 12:00-18:00 bracket in Azshara (Bay of Storms). Did a 6 hour test yesterday and it's nothing like what it used to be at roughly 33% catch rate between those times.

My calculations:

777 catches in 6 hours
80 being Winter Squid
9.7125 % chance of Winter Squid
13.3 Winter Squid p/h

Is there something that can be done about this catch rate because at the moment, there doesn't seem to be a place that is worthwhile fishing them. It seems a flat 10% or so all around the locations, was this intended by Elysium to be different or can you change it?

UPDATE (25/02/18): I should note, all of this was tested with 300/300 fishing skill, +100 from lure, +20 from pole, +2 from glove enchant. It was all fished at location 55.0, 61.6 in Bay of Storms, Azshara. Also note that frequently I get a catch with empty loot in it. Calculating today how many missed loot I get per hour and will post another list of calculations.

**Comment by bk187** [comment]
It should be 20% I think on that area

**Comment by nexiros** [comment]
Regardless, I remember back in the day I got around 1/3. Not 1/10. If its 1/5 that would be a lot better than it is now...

**Comment by Navashed** [comment]
Old comments suggest a 10% drop rate is correct at these times:

https://web.archive.org/web/20070314054853/http://www.thottbot.com:80/i13755
http://web.archive.org/web/20060527170605/http://wow.allakhazam.com:80/db/item.html?witem=13755

I can't find any information to support a 20% or greater drop rate.

**Comment by nexiros** [comment]
I know this isn't Thott or Ala but: https://legacy-wow.com/fishing-guide-variation-by-time/

There has always been a 6 hour time rule when it came to fishing, some fish would change rates at different times and some fish would flat out be unavailable to catch. For instance between 00:00-06:00, the chances of anyone finding a Winter Squid was pretty much zero if not zero. However I remember as do others in our guild that when 12:00 hit, we'd farm Winter Squid because its catch rate increased to around 1/3. It seems like all zones from my experience have a flat rate of 10% and don't even change between times.

Name is Quiver from Indominus btw and we're very much hoping that this issue is sorted as is the missing loot with caught fish before the winter season ends. Spending 6 hours constantly fishing to only get 80 Winter Squid is kind of heart breaking at the moment.

**Comment by Navashed** [comment]
That guide claims to have been written in 2006 which makes it the best available authority on these drop rates. He lumps the seasonal fish (Winter Squid/Summer Bass) together into a single category and since he was writing in the summer he could only collect data for Summer Bass. I think it is reasonable to assume the behavior of the Summer Bass and Winter Squid mirror one another.

That said, in his "Summary" section he lists the "normal" drop rate of Summer Bass at 10% and the "bonus" drop rate (in the afternoon) at 15%. The data he links supports this estimation.

As far as I am concerned, this is enough evidence to set the afternoon rate to 15%, if it isn't already.

**Comment by nexiros** [comment]
"Variation by time means that data from sources such as Thott is misleading: We do not know what time of day catches were recorded."

That's why I'd never trust Thott in regards to fishing. Doesn't take into account time they were caught.

**Comment by Navashed** [comment]
Yes, the values there are not useful. I linked Thottbot and Allakhazam to examine the comments. The comments seemed to agree the drop rate was low in general, lower than 20%. Again, the fishing guide you linked has persuaded me that the "peak hours" drop rate should be 15%. I will check the value during those hours tomorrow if I am able.

For what it's worth, that guide also says the midnight-6am drop rate should be 0%; it is currently 5%.

**Comment by nexiros** [comment]
You're right to a certain degree Navashed, but we've just been trying to see what's wrong and we've seen. The reason why it's 15% and not 33% is because the table you're talking about (regarding the Summer Bass) was conducted in Feathermoon Stronghold, NOT Bay of Storms, Azshara.
So you're correct, it should be increased to 15% in that area but in Bay of Storms it was boosted higher. See my initial link. Those are the sort of drop rate differences.

**Comment by nexiros** [comment]
Even if you guys felt that 33% was too much for this server to handle in the Bay of Storms area, you could at least increase it to a 1/4 drop rate for that very specific location in which we remember it was very high. Whats your take on it?

**Comment by Navashed** [comment]
Fishing loot tables go by zone, not by specific regions like "Bay of Storms." So it would have to be all of Azshara.

**Comment by nexiros** [comment]
Erm, you do realise that that just isn't the case. I never miss off say the coast of Azshara or Lake Mennar in Azshara. Also the variety of fish changes in all of those areas. For instance the fish I receive in Bay of Storms area include things like Darkclaw Lobster and Large Raw Mightfish. In the other areas, I can't fish those AT ALL. Also the chances of getting a WS in anywhere BUT the Bay of Storms in Azshara is very slim.

**Comment by Navashed** [comment]
After digging through the database a bit, I see fishing is supposed to have specific regions. As far as I know, this is not implemented.

"Bay of Storms Fishing"
https://web.archive.org/web/20060708044149/http://www.thottbot.com:80/?n=30434

Searching for a fishing loot table by this number comes up with nothing in the database. Searching by zone number gives a loot table. The only loot tables which yield any results correspond to zone IDs.

**Comment by Novat93** [comment]
That is flat out wrong.

The very Thottbot comments you cite above clearly gives credit to Winter Squid being available in the ''Jaguero Isle'' sub-section of the Stranglethorn Vale zone. The decision to overlap fishing skills, within zones was likely taken due to the fact that allot of zones don't follow the standard 10-20, 20-30 etc level range.

Jaguero Isle for example contain level 50 mobs, while the most northern part of Stranglethorn Vale contain level 30 mobs. It's clear that the developers expected that higher level players completing lvl 50 elite quests, would have significantly higher fishing skill. Thus a sub-section was created.

https://classicdb.ch/?object=2040

This is the map for Mithril ore. Clearly showing a preference for placing the ore deposits in higher level areas, within a zone. The southern part, the Kurzen cave and the elite ogre cave. All contain Mithril ore, while the northern part of the zone shows no deposits (except the mentioned kurzen cave).

I'm on my way to do some in game testing, on live Elysium to see if i can catch any fish at all in the bay of storm with 206 skill + 20 skill from rod, then +100 from lure. Then test elsewhere in the zone where the ''bay of storm'' tag does not apply.

**Comment by nexiros** [comment]
It is implemented I can assure you, Elysium has different fish tables with different drop rates within specific regions. This comes from many hours of fishing xD
Again, with Thottbot, I don't look at the drop% because they don't take into account times of day but you're right, they are supposed to have specific regions (which they do already). The problem is, that the drop rate in these very specific regions is off for the Winter Squid which I remember bit really hard between the hours of 12:00-18:00.

**Comment by Navashed** [comment]
I am not seeing any clear distinction between what I'm fishing at Jaguero Isle and near Grom'gol.

**Comment by Novat93** [comment]
Testing live, on the Nighthaven server.

Fishing in the Azshara zone with the ''bay of storms'' tag, above the minimap. It's impossible to fish for me as the client side requirement to fish there should be 330 to throw a line, with a 425 requirement to never lose a fish due to random chance.

However, moving further south. With the ''Ruined Reaches'' map tag. I can easily catch fish with 326 fishing skill. As the fishing requirement here should be 205, with a requirement of 300 to never lose a fish due to rng.

**Comment by Navashed** [comment]
I see, there is a clear distinction between what is fished in the Bay of Storms and elsewhere in Azshara. I am still not sure how to access these region-specific loot tables, but that's fine. I will support changing the Winter Squid drop rates to the values demonstrated in that fishing guide from 2006.

Winter Squid drop rates (in winter):

Bay of Storms region in Azshara
00:00 - 06:00 : 10%
06:00 - 12:00 : 15%
12:00 - 18:00 : 30%
18:00 - 00:00 : 15%

Other regions listed here: https://web.archive.org/web/20070314054853/http://www.thottbot.com:80/i13755 
00:00 - 06:00 : 0%
06:00 - 12:00 : 10%
12:00 - 18:00 : 15%
18:00 - 00:00 : 10%

**Comment by nexiros** [comment]
Thank you for this. Hopefully it is fixed soon. Will you let us know when it's been changed?

**Comment by Navashed** [comment]
Issue will be marked as "Fixed" when a change has been made.

**Comment by Navashed** [comment]
I figured it out. Fishing regions within individual zones can be found under their respective "subzone ID." For Bay of Storms, for example, this number is 1227.

A full list of subzone IDs, which was difficult to find, can be seen here: http://rgtc.wikia.com/wiki/AreaTable.dbc_tc2

**Comment by nexiros** [comment]
Cool, hopefully this will aid you guys in the changes in drop rates quoted :) Good job on finding the information. Appreciate the time you're putting into this issue.

**Comment by nexiros** [comment]
Any ETA of a patch to fix this bug? Winter seasons ends on March 19th and want to fish again :( Thanks for any info you can provide.

**Comment by Novat93** [comment]
Agree with Nexiros, it's a rather time sensitive bug. Fixing it in 3 weeks serves no purpose. It has to be fixed prior to Winter Squids leaving Azeroth for the summer. Preferably as soon as possible.

**Comment by Ooooom** [comment]
Any update? :S

**Comment by Lightsockie** [comment]
Seconding drop rates being off. The drop rates for the squid are wrong in Feleras, too. I'll update with my gathered data and what they should be soonTM. But hoping on the confirm train now

**Comment by Navashed** [comment]
The dev team apologizes for the delay. A fix is still a few days off. The Winter Squid season may be extended to make up for this bug.

**Comment by Ooooom** [comment]
So, the fix was done yet or? Because apparently the drop rate is improved but no where close to the 30% suggested during the peak hours in BoS. Also, can you please let us know the date when WS are unable to be fished anymore as apparently you can still catch them in other area's in Azshara like Temple of Arkkoran.

**Comment by Thenari** [comment]
Its been a long time. I dont think winter squid can be caught right now ill ask when they come back

**Comment by Thenari** [comment]
Since winter squid cant even be caught now im marking this low priority but i hope our few devs get a chance to look into this before next winter.
