### ISSUE TITLE
PvP Spell Hit not scaling properly with level

### ISSUE THREAD

**Issue by Crusaderz** [elysium-project/classic-bug-tracker#477]
Разница в уровне дает слишком большой шанс промаха в пвп.

Ранее я репортил этот баг: https://github.com/elysium-project/bug-tracker/issues/20 который был отмечен, как исправленный.

После фикса дела действительно стали лучше, но шанс все еще высокий и близко не похож на близзовскую механику 2006 года.

В 2006 я играл рогой, локом, пристом, друидом, шаманом на офе. В том числе активно пвпшился в мире\бг. У кастеров не было никаких проблем с игроками выше на десяток уровней. Что вполне логично, ведь близзы сделали возможность встретить игрока на 9 уровней старше на БГ и было бы странно, если бы они не предусмотрели возможность игрокам самого нижнего уровня в диапазоне x0 - x9 влиять на ход битв.

Сейчас на сервере 7 уровней разницы уже неприятно влияют на шанс промаха. 4 резиста спеллов подряд в такой ситуации - обычное дело. И это **не близзлайк**.

В защиту утверждения того, что игроки не имели проблем против игроков на десяток уровней выше:
https://youtu.be/XqTfP-Gnj0U?t=1013
Видео опубликовано мной. Находилось в архиве warcraftmovies.com (архив доступен премимм аккаунтам). 
На видео 38 лок против 52 воина. 14 уровней разницы. 16 кастов и **2** резиста.

Понимание того, что шанс промаха на элизиуме все еще **сильно** отличается от близзовского пришло после нескольких "схваток" моего 29 лока с 60 хантом. 

Этот хант ради развлечения убил меня различными способами 5 раз за час. Только петом или только в мили, высасывание маны и прочее. С моей стороны была возможность кастовать в него спеллы длительное время, пока он прыгает вокруг меня и развлекается.

Максимальное количество заклинаний, которое я успевал использовать по нему за один "сеанс" ганка превышало два десятка. За все 5 встреч с ним ни один спелл на него лег. Все срезистил.

А теперь глянем аналогичную ситуацию: 29 маг против 60 роги, видео было залито в апреле 2006
https://www.youtube.com/watch?v=o3GsLK2o7Xk
На видео группа 29 твинков убивает рогу 11 ранга (Commander) Из 17 кастов у мага резистятся **7**
Я уж не говорю про доты от приста, дебафф майндфлая и замедляющего яда от других игроков. Это все касты.

Еще раз:
20+ кастов на элизиуме по 60й цели на 29 уровне, **0** попаданий.
17 кастов на офе в ванниле по 60 цели на 29 уровне, **10** попаданий.

Кстати, на форуме nostalrius begins в свое время игроки так же подняли тему неадекватно высоких промахов: https://forum.nostalrius.org/viewtopic.php?f=45&t=3288

В этой теме участник, защищающий высокий шанс промаха спеллами нашел официальный пост 2005 года:
https://web.archive.org/web/20060529065634/http://forums.worldofwarcraft.com/thread.aspx?fn=blizzard-archive&t=37&p=1&tmp=1#post37
в котором представитель близзов написал формулу промахов:
4% в случае, если кастер и его цель одинакового уровня,
5% если цель на уровень выше
6% если цель на 2 уровня выше
Ну а дальше по +7% за разницу в уровне.
Позже этот участник признал, что эта формула не верна, ведь согласно этой формуле при разнице в 14 уровней шанс промаха 90%. Но есть множество видео тех времен (есть по ссылке на предыдущий баг репорт), на которых кастеры спокойно кастуют спеллы в высокоуровневых противников с разницей более чем в 14 уровней. А этого не должно происходить.

Итак есть два факта:
1. Шанс промаха на сервере не верный.
2. Официальный шанс промаха не известен.

В этих условиях я предлагаю применить кастомную формулу, в которой % промаха будет всё так же зависеть от уровня, но рост его будет более "мягким":

ROUND( 100 - ( LEVELDIFF / 10 * FLOOR( LEVELDIFF / 10 ) + LEVELDIFF + 4 ) )

На выходе имеем:

![image](https://user-images.githubusercontent.com/3641625/36633267-51e70cbe-19a3-11e8-8e13-992b0c658a08.png)

Одинаковые уровни противника и кастера - шанс промаха 4%, как и должно быть.
Дальше до 9 уровней разницы (хорошо для БГ) по одному шансу за уровень.
14 уровней разница - шанс хита 81% (похоже на видео 38 лок vs 52 вар).
31 уровень разница - шанс хита 56% (похоже на видео 29 мага против 60 роги)

Почему это важно? Потому, что текущая механика на элизиуме это не blizzlike experience.
Blizzlike experience - возможность избежать смерти при встрече с высокоуровневыми игроками, путём использования овцы, страха, корней, ловушки и бега прочь.
Blizzlike experience -  возможность убийства высокоуровневого игрока группой лоулевельных кастеров.
Blizzlike experience - удачный бой против игрока на десяток левлов выше, где ты победил за счет скилла. А не когда он побеждает из-за того, что резистит добрую половину твоих спеллов.

Всего этого игроки элизиума лишены.

**Comment by Navashed** [comment]
You are correct that spell hit chance scales incorrectly against higher level players in PvP. The difference between Blizzlike behavior and the behavior here is dramatic.

However, applying a custom formula which attempts to approximate Blizzlike behavior without rigorous evidence is an unsatisfying solution. Perhaps a more thorough investigation could be done by collecting data from old videos which demonstrate lower level players casting spells at higher level ones.

**Comment by Crusaderz** [comment]
Yes i'm fully aware about +hit talents. They indeed help, but initial hit chance was big enough already.

Same 14 levels difference, 46 shaman vs 60 druid (knight-champion). No hit talents (you have to be level 53 for a +3 hit talent from a resto tree and still having stomrstrike).
https://www.youtube.com/watch?v=ufizLILcCPU 8 shocks used, 1 shock resisted (some resists are from thorns buff proc)

> Perhaps a more thorough investigation could be done by collecting data from old videos which demonstrate lower level players casting spells at higher level ones.

It's not possible. I've researched this topic for a very long time, looking everywhere, even had to buy warcraftmovies premium account (archive access) and still there is not enough low level vs high level videos. Back in vanilla times video.google.com was popular, lots of wow movies were there and it's all lost after shutdown. 
Some videos in this thread and some in my previous bug report, it's all we've got.

> However, applying a custom formula which attempts to approximate Blizzlike behavior without rigorous evidence is an unsatisfying solution.

Elysium already did it. After my first bug report https://github.com/elysium-project/bug-tracker/issues/20 the changes were made. It's not accurate, but it's much better than it was before.
So if you change current custom formula again it will not cause any harm to the game. Lowlevel players won't faceroll someone ten levels higher, since higher level player already have better stats, gear and spell ranks. Low level player will have a chance to win and thats how it supposed to be.

**Comment by Navashed** [comment]
Let's continue to discuss what data we have.

In your previous bug report you linked this video: https://www.youtube.com/watch?v=InXWMGxOfEo
What can we learn from this?
First of all, he is actively trying to find high level players and gank them for fraps. From this we can assume 2 things:
1) He probably had many fights against 60s where his spells were resisted, he lost, and he didn't include them in the video.
2) He probably made his spec specifically for killing 60s, which means 5/5 Shadow Focus (+10% hit chance).

Analyzing his fights shows us that he almost certainly had 5/5 Shadow Focus. He had 0/5 Spirit Tap since Spirit Tap never proc'd after he got a kill. He also had 0/5 Shadow Weaving since that debuff was never applied. Yet he had at least 31 points in Shadow for Shadowform. So we can safely conclude he did have 5/5 Shadow Focus and thus 10% additional hit.

He fights two different 60 mages in duels. Both use Mage Armor and even despite this shadow resistance he has a 100% hit rate in both fights. This is a clear example of him only using the best footage out of many, many duels. Therefore we should disregard his dueling footage.

His world PvP fights are more trustworthy. Again he must have selected only the best out of many fights, but it is more difficult to get a large sample size of world PvP encounters than it is duels in front of Org. So I trust his two world PvP fights vs 60s much more.

In the first such fight he faces what appears to be another 60 mage. He hits this opponent 12 levels above him 14 times out of 18 casts for a hit rate of 77.8%.
In the second fight he faces a 60 warrior, again 12 levels up. He hits her 12 times out of 17 casts for a hit rate of 70.6%.
Combining the data from these two encounters, we get 26 hits out of 35 casts -- 74.3%. Subtracting his 10% hit from talents, this suggests a ~64% base hit chance at -12. This is already frustratingly low, and 12 levels is not that much.

You also linked this video: https://www.youtube.com/watch?v=qZD4KmR7tb8
He claims to be 0/40/0 which means no hit talents. From what I can see in the video, this is correct (he has Master of Elements, Ignite, Impact, Imp Scorch, Imp Fireball, Imp Fire Blast, Flame Throwing etc). His hit chance should be an accurate reflection of his level difference.
In the clip starting at 1:34 he is 47 against a 60 hunter. With this 13 level difference, he lands 8 resistable spells (Ignite, the Blast Nova daze, and the Pyro/Fireball dots are not independently resistable) out of 16 casts (including a bunch of Ice Armor applications and resists). This is a 50% hit chance.

All fights in his video:
14 level difference - 3 casts - 2 hits - 66.7%
14 level difference - 5 casts - 4 hits - 80%
13 level difference - 16 casts - 8 hits - 50%
13 level difference - 10 casts - 10 hits - 100%
12 level difference - 6 casts - 6 hits - 100%
11 level difference - 3 casts - 3 hits - 100%
11 level difference - 11 casts - 8 hits - 72.7%
11 level difference - 11 casts - 9 hits - 81.8%
11 level difference - 8 casts - 6 hits - 75%
11 level difference - 11 casts - 9 hits - 81.8%
11 level difference - 6 casts - 5 hits - 83.3%
11 level difference - 5 casts - 5 hits - 100%
11 level difference - 6 casts - 4 hits - 66.7%
11 level difference - 7 casts - 7 hits - 100%
11 level difference - 5 casts - 4 hits - 80%
11 level difference - 22 casts - 19 hits - 86.4%

Combining all of our data up to this point (and subtracting 10% hit from the shadow priest):
-14 total: 8 casts - 6 hits - 75%
-13 total: 26 casts - 18 hits - 69%
-12 total: 41 casts - 28.5 hits - 70%
-11 total: 95 casts - 79 hits - 83%
Again remember they are selecting only the best clips.

From this data we can confidently conclude the old values stated by Tseric are incorrect (ex: 73% at -5). However, the values generated by your formula are too generous (ex: 81% at -14).

**Comment by Crusaderz** [comment]
>13 level difference - 16 casts - 8 hits - 50% 

Thats more like series of unfortunate events, since level 29 mage landed 10 out of 17 spells against level 60 rogue - 60%. 
50% if we assume he had Arcane Focus. 2 out of 17 spells were fire blast and both landed ("resist" appears right after fire blast damage, mage definitely had Impact talent and proc resisted)
impact, imp. arcane missle, clearcast. 5 points left. Whether he had Arcane Focus is highly debatable. 

Anyway, 31 level difference is a 56% chance to hit according to the proposed formula. Sounds about right. Just adjust it around a bit.

Raid group of 29 vs 60, sadly not from caster POV:
https://www.youtube.com/watch?v=cv93-0TNX98

Also i think min cap should be implemented. Many years ago i've seen video where bunch of level 1 attacked 60 paladin in durotar. There were successful spell hits. I can't find it anymore, but i found a similar video from TBC era, level 1 vs 65+ druid (his staff from Nagrand quest, aviable at level 65), 3 hits out of 7, atleast 64 levels difference, definitely min cap existed on retail back then.
https://www.youtube.com/watch?v=sR5k8S4hLCg

Also just to show that nothing has changed in TBC (elysium next expansion):
37 vs 60
https://www.youtube.com/watch?v=lpbRqAbX3QU

**Comment by Navashed** [comment]
A miss cap is an interesting idea. I was already considering it but that video of the level 1s is very compelling. They are definitely getting a lot of hits. Someone in the Nost thread you linked above said "Melee rolls have a mechanic where chance to miss caps at 60%, is there supposed to be something similar for spells?" I have never heard of this mechanic but it seems plausible.

Let's take a closer look at the level 1 video. Does this support a 40% minimum hit chance? I don't think so. You can see the "resist" animation, a black disk, pop up on the bear very often. The Fireball dot is applied infrequently. It's difficult to get a precise count of the number of Fireballs flying at the bear vs the number of dots applied but it is certainly less than 40%. It is such a large sample size however that I think it would be worthwhile to try to get an accurate count.

**Comment by Crusaderz** [comment]
>You can see the "resist" animation, a black disk, pop up on the bear very often. The Fireball dot is applied infrequently. It's difficult to get a precise count of the number of Fireballs flying at the bear vs the number of dots applied but it is certainly less than 40%.

We should consider magic resistances given by "mark of the wild" buff. They could cause both full and partial resists and we can see shadow bolt hitting for 7 damage instead of 14.

BTW, there also level 70 shaman (epic helm and shoulders).

>certainly less than 40%.
I think it's around 30% or so.

**Comment by Navashed** [comment]
>I think it's around 30% or so.
Let's examine the video further.
Looking at the clip at 1:23: the POV player targets a boar instead of the druid but we can watch the druid for animations of being hit by fire damage to ascertain a hit rate.

Fireballs/Firebolts casted on druid:
1:27 - 3
1:28 - 2
1:29 - 4
1:30 - 1
1:31 - 2
1:32 - 4
1:33 - 0
1:34 - 3
1:35 - 0
1:36 - 4
1:37 - 2
1:38 - 2
1:39 - 4
1:40 - 2
1:41 - 0
1:42 - 3
1:43 - 3
1:44 - 1
1:45 - 4
Total: 44

Hit animations:
1:30 - 1
1:32 - 1
1:33 - 1
1:40 - 2
1:43 - 1
1:44 - 1
1:45 - 1
Total: 8

8/44 = 18.2% hit rate. Some of these animations could be multiple Fireballs hitting at the same time however. Generously considering 50% of the hits to be double-hits (though I think there are probably only 2 at most, not 4) gives us 12/44 = 27.3%.

The clip of the shaman being turreted by a swarm of gnomes at 2:39 is also useful. By my count there are 15 mages casting Fireball and a maximum of 6 Fireball dots on the target. Let's be generous and use this maximum of 6. The dot lasts long enough to cast 2 Fireballs (with change), however not all gnomes were chain casting.

Assuming none of them were chain casting, 6 dots = 6 hits from 15 mages = 40% hit rate.
Assuming all of them were chain casting, 6 hits over 2 volleys is 3 hits per volley. 3 hits / 15 mages = 20% hit rate.
So the true hit rate lies between 20-40%.

Combining the data from both clips we come up with a hit rate somewhere from 1 in 5 to 1 in 3. Your estimation of "around 30%" seems fair. Personally I think the proper value is closer to 25% but we do not have enough evidence to support such fine distinctions.

**Comment by Thenari** [comment]
This is pretty old im not even sure if @Navashed is still with us.

It used to have a title i could not even read so i never looked into it.

**Comment by Crusaderz** [comment]
Hey @Thenari  It's still broken, why you closed it?

**Comment by Thenari** [comment]
Im testing a bot. Itll be checking for stale issues that have no progress
