### ISSUE TITLE
Winterfall Beads

### ISSUE THREAD

**Issue by MerryweatherKT** [elysium-project/classic-bug-tracker#841]
They aren't dropping from the Winterfall mobs.

**Comment by MerryweatherKT** [comment]
Thanks

**Comment by Thenari** [comment]
IRL busy busy (sept 1 is when a lot of schools and housing things happen without giving a lot of detail)
I was talking to people who tell me the feathers work and i went and got the quest from the white furbolg lady but got distracted or something before i had a chance to kill any winterfall bears for look for beads.

**Comment by Thenari** [comment]
I am confirming this though as enough people have tested it and with the feathers working in felwood its almost certainly the beads being wrong

**Comment by Thenari** [comment]
Im unsure its not exactly a High Priority but it wont fix itself with a future patch and not niche its quite generally so i dont wanna label it low priority.

**Comment by RainElysium** [comment]
Previous "fix" didn't ... "fix". I've now .... fixed. No quotations.

Keeping mind that since 1.9 quest "Winterfall Activity" shouldn't be repeatable, and now has quest rewards. Its been fixed as per:

![image](https://user-images.githubusercontent.com/33706636/45452142-2ae34380-b6ab-11e8-9eed-dca8c7145c2b.png)
