### ISSUE TITLE
[Libram: Blessing of Might VII] Dropping on horde side

### ISSUE THREAD

**Issue by taleus** [elysium-project/classic-bug-tracker#862]
Dropping for horde.

**Comment by Thenari** [comment]
Pally loot drops in horde raids and shammy drops for ally raids. I do not believe the raid cares who you are you get a random loot table regardless. Raids dont discriminate.

But maybe im wrong :p

Im guessing this is AQ?

**Comment by taleus** [comment]
Yes, its AQ 20.  Horde aint suppose to get Ally loot.

**Comment by Thenari** [comment]
punctured voodoo dolls for paladians drop ;P I'm pretty sure this is an invalid post. 

So instead of you forcing the burden of truth on me lets go to you :P Can you provide a source saying that the wow original blizz dev team bothered to do loot table check based on what faction was in the raid/instance until then im doing an invalid close.

Btw that libram blessing of might you can put on neutral AH so go ahead and sell it :)
