### ISSUE TITLE
Bugged mobs blocking The Family Crypt Quest

### ISSUE THREAD

**Issue by EvilNecroid** [elysium-project/classic-bug-tracker#971]
I have done this quest like a million times on many different characters and i know the quest pretty well but today when i tried to go into the crypt i killed a guy in the stairs leading in which was normal but i was expecting to see a zombie at the bottom of the stairs only for some reason he wasnt where he should be. so i peaked around the corner and in 1 direction there was nothing which is wrong because there should be some guys in the corner and in the other direction i could see 2 guys but as soon as they see me i get about 5 guys on my head instantly. its like they r coming out of the walls or something. now these r lvl10 mobs and i was lvl 13 and still could not survive no matter how hard i tried so i had to get a GM to mark the quest as complete

**Comment by Vasquez-QA** [comment]
Incorrect Mob Placement - 3x "Rotting Ancestor" (GUID 1530) and 1 x "Wailing Ancestor" (GUID 1534) spawn together in "The Agamand Family Crypt"located in the Tirisfal Glades. 

The pack spawn to the right as you reach the bottom of the first stair case however none spawn on the opposite side (see photos) where they should. Due to the close proximity all 4 mobs will pull together if one is body pulled at the base of the stairs, making the quest difficult / impossible to solo at the appropriate level.

Two of these mobs need to be moved to the other side of the corridor.

Photo of Pack of 4:

![image](https://user-images.githubusercontent.com/2932176/48982418-03ace780-f0da-11e8-9dd6-9c4444aafe95.png)

Photo of opposite side (no mobs):

![image](https://user-images.githubusercontent.com/2932176/48982425-12939a00-f0da-11e8-92fe-cf4ea6606557.png)

**Comment by RainElysium** [comment]
Fixed. Will be applied upon next server restart.
